[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/widget-api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, x-api-key"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/widget-api/*"
  to = "/.netlify/functions/:splat"
  status = 200