[build]
  functions = "netlify/functions"
  
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "netlify/functions/elevenlabs-signed-url.js,netlify/functions/mobile-a1.js"

[[redirects]]
  from = "/A1/mobile"
  to = "/.netlify/functions/mobile-a1"
  status = 200

[[redirects]]
  from = "/A1"
  to = "/.netlify/functions/mobile-a1"
  status = 200
  conditions = {header = {user-agent = ["*Mobile*", "*Android*", "*iPhone*", "*iPad*", "*iPod*"]}}

[[redirects]]
  from = "/A1"
  to = "/A1/index.html"
  status = 200

[[redirects]]
  from = "/a1"
  to = "/A1/index.html"
  status = 200

[[redirects]]
  from = "/A1/*"
  to = "/A1/index.html"
  status = 200

[[redirects]]
  from = "/a1/*"
  to = "/A1/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200